### ISSUE TITLE
ESP32 reboots all 5 to 10 minutes

### ISSUE THREAD

**Issue by frimtec** [klaasnicolaas/home-assistant-glow#61]
Hi there

Many thanks for this great project.

I created a home-assistant-glow with a "Node MCU ESP32" from Joy-it.
Almost everything works fine, the impulses from the power meter are recognized correctly. 
But what is weird, the ESP32 seems to restart every 5 to 10 minutes. 
This can be recognized by the fact that the home-assistant-glow device is not available for a few seconds in HA and when back, the total energy counter is reset to 0.

At first I thought this is due to electromagnetic interference.
Therefore I've kept the wires between the sensor and the ESP32 extremely short and I've installed a ferrite ring on the incoming USB power cable.
Unfortunately, this did not change anything at all. The reboots are still in the same frequency, between 5 to 10 minutes. 

Does anyone have any idea what the cause for these reboots could be?

Is there a watchdog on the device that is not triggered correctly? 
Could interference be interspersed on the reset/en signal?

**Comment by frimtec** [comment]
Have found the following in the log at the time of the reboot or maybe better called reset:
```
[18:13:58][D][sensor:121]: 'House - Power consumption': Sending state 2368.42090 W with 0 decimals of accuracy
[18:13:58][D][light:035]: 'Red' Setting:
[18:13:58][D][light:046]:   State: ON
[18:13:58][D][sensor:121]: 'House - Total energy': Sending state 0.08800 kWh with 3 decimals of accuracy
[18:13:58][D][light:035]: 'Red' Setting:
[18:13:58][D][light:046]:   State: OFF
[18:14:01][D][sensor:121]: 'House - Power consumption': Sending state 2364.53198 W with 0 decimals of accuracy
[18:14:01][D][light:035]: 'Red' Setting:
[18:14:01][D][light:046]:   State: ON
INFO home-assistant-glow.local: Unexpected error while reading incoming messages: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 505, in run_forever
    await self._run_once()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 480, in _run_once
    pkt = await self._frame_helper.read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 219, in read_packet
    return await self._read_packet_plaintext()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 197, in _read_packet_plaintext
    preamble = await self._reader.readexactly(1)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for home-assistant-glow.local
WARNING Disconnected from API
INFO Successfully connected to home-assistant-glow.local
[18:14:13][D][light:035]: 'Red' Setting:
[18:14:13][D][light:046]:   State: OFF
[18:14:16][D][api:095]: Accepted 192.168.1.2
[18:14:16][D][api.connection:727]: Home Assistant 2021.9.7 (192.168.1.2): Connected successfully
[18:14:16][D][sensor:121]: 'House - Power consumption': Sending state 2367.64233 W with 0 decimals of accuracy
[18:14:16][D][light:035]: 'Red' Setting:
[18:14:16][D][light:046]:   State: ON
````

**Comment by frimtec** [comment]
I just received and installed a new "Node MCU ESP32" device. 
Now all works well.
There must have been an hardware defect on my previous device.
